SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#radius of the players ship
PLAYER_RADIUS = 20
#width of the lines hat draw the players ship
LINE_WIDTH = 2

#player turning speed (Moving around)
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Shooting
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500

#Cooldown in the shooting
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
